version: '3.1'

networks:
  test_network:

services:
  test_db:
    container_name: test_database
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/data/postgres"
    env_file:
      - .env
    volumes:
      - ./assets/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - test_network
    restart: always

  test:
    container_name: tester
    build:
      context: .
      dockerfile: test.dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: "test_db:5432"
      PGDATA: "/data/postgres"
    env_file:
      - .env
    networks:
      - test_network
    depends_on:
      - test_db

